kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cert-manager-claim
  namespace: kube-system
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
