apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: whereisaaron/kube-cert-manager:0.4.0
          env:
          - name: GCE_PROJECT
            value: production-176219
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /cred/dnscred-prod.json
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
            - name: credentials
              readOnly: true
              mountPath: "/cred"
        - name: kubectl-proxy
          image: palmstonegames/kubectl-proxy:1.4.0
      volumes:
        - name: credentials
          secret:
            secretName: dns-credentials
        - name: data
          persistentVolumeClaim:
            claimName: cert-manager-claim
