apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: jlcrow/kube-cert-manager:0.5.0
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
            - "-class="
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
            - name: credentials
              readOnly: true
              mountPath: "/cred"
        - name: data
          persistentVolumeClaim:
            claimName: cert-manager-claim
